import { Component, OnInit } from '@angular/core';
import { Hero } from './hero';
import { HEROES } from './mock-heros';

// Metadata properties generated by angular of the component
@Component({
  selector: 'app-heros',
  templateUrl: './heros.component.html',
  styleUrls: ['./heros.component.css']
})

export class HerosComponent implements OnInit {

  // Single hero from class
  hero: Hero = {
    id: 1,
    name: 'windstorm'
  };

  // Exposing list of heros from mock-data
  heros = HEROES;

  // No hero selected on init
  selectedHero: Hero;

  constructor() { }

  // ngOnInit is a lifecycle hook angular calls after creating the component
  // its a good place to put initialization logic
  ngOnInit() {
  }

  // Respond to hero click event
  onSelect(hero) {
    this.selectedHero = hero;
  }
}
